sudo: required
services:
  - docker

before_install:
  - docker build -t seonaidl/docker-react -f Dockerfile.dev .
# The name of the tag doesn't really matter because it is local and temporary, but this
# form is good practice

script: 
  - docker run seonaidl/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-275952397337"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    # this may have to be put into double quotes, according to the video
    secure: $AWS_SECRET_KEY